name: tag-build-release
run-name: Building version ${{ github.ref_name }} of ${{ github.repository }}

permissions:
  contents: write

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  docker-build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build docker image 
        run: |
          docker build -t ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_IMAGE }}:${{ github.ref_name }} .

      - name: Tag latest image
        run: |
          docker tag ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_IMAGE }}:${{ github.ref_name }} \
          ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_IMAGE }}:latest

      - name: Login to dockerhub
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" \
          | docker login -u ${{ vars.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push to dockerhub
        run: |
          docker push ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_IMAGE }}:${{ github.ref_name }} && \
          docker push ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_IMAGE }}:latest

  release:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate release md
        run: |
          cat <<EOF > release.md
          ## Container Image

          https://hub.docker.com/repository/docker/${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_IMAGE }}/tags/${{ github.ref_name }}
          EOF

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body_path: release.md
          draft: false
          prerelease: false
